/* DO NOT EDIT. THIS FILE IS AUTOGENERATED. */
import { Alert } from "@/features/admin/drizzle-admin/drizzle-ui";
import { ConstructionIcon } from "lucide-react";

export default async function Page() {
  return (
    <div className="p-5">
      <Alert variant="muted">
        <ConstructionIcon /> Welcome to Admin. Use this space to build a dashboard home page. <ConstructionIcon />
      </Alert>
    </div>
  );
}
