/* DO NOT EDIT. THIS FILE IS AUTOGENERATED. */
import { usersTableConfig } from "@/app/(admin)/_lib/users-table.config";
import { db } from "@/lib/db/db";
import { DrizzleAdminConfig } from "@/lib/drizzle-admin/types";

export const config: DrizzleAdminConfig = {
  basePath: "/admin",
  schema: {
    users: usersTableConfig,
  },
  db: db,
  dbDialect: "sqlite",
  paginationOpts: { enablePageInput: true, buttonVariant: "info", perPageInputType: "text" }
};
