/* DO NOT EDIT. THIS FILE IS AUTOGENERATED. */
import {
  UserDeletePageNav,
  UserEditPageNav,
  UserListPageNav,
  UserRoleCustomFormControl,
  UserRowNav,
  UserViewPageNav,
} from "@/app/(admin)/_components/users-components";
import { DrizzleTableConfig } from "@/lib/drizzle-admin/types";
import { users } from "@/schema/users";
import type { ComponentType } from "react";

const adminComponents: Record<string, ComponentType<object>> = {
  RowNav: UserRowNav as ComponentType<object>,
  ViewPageNav: UserViewPageNav as ComponentType<object>,
  EditPageNav: UserEditPageNav as ComponentType<object>,
  DeletePageNav: UserDeletePageNav as ComponentType<object>,
  ListPageNav: UserListPageNav as ComponentType<object>,
};

export const usersTableConfig: DrizzleTableConfig = {
  drizzleTable: users,
  formControlMap: { image: "file", role: "custom" },
  customFormControlMap: { role: UserRoleCustomFormControl },
  components: adminComponents,
};
