/* DO NOT EDIT. THIS FILE IS AUTOGENERATED. */
import { DarkModeScript } from "@/lib/drizzle-admin/drizzle-ui";
import { AdminLayout } from "./_components/admin_layout";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <AdminLayout>
      {children}
      <DarkModeScript />
    </AdminLayout>
  );
}
